[package]
name = "scratch"
version = "0.1"
lean_version = "3.4.2"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "08977be6c38f2a5c361d5b02da1b7dc636c844b9"}
